# Generated by Django 4.2.11 on 2024-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_itemdetails_itemsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_product', models.IntegerField()),
                ('Id_user', models.IntegerField()),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('discounts', models.FloatField()),
                ('net', models.FloatField()),
                ('state', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
