# Generated by Django 4.2.11 on 2024-03-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='state',
            new_name='status',
        ),
    ]
